scrape_configs:
  - job_name: 't1-demo-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          alias: "t1_java_demo"